version: '3'
services:
    sonarqube:
        container_name: sonarqube
        image: sonarqube:latest
        ports:
            - '9000:9000'
            - '9092:9092'
        volumes:
            - ./conf:/opt/sonarqube/conf
            - ./data:/opt/sonarqube/data
            - ./logs:/opt/sonarqube/logs
            - ./extensions:/opt/sonarqube/extensions
